
Random Tech Blog
Linux, Networking, and DevOps Notes

title: “Random Tech Blog” description: “Linux, Networking, and DevOps Notes” author: “Dhirandar”

remote_theme: pages-themes/cayman@v0.2.0 plugins:

    jekyll-remote-theme

nav_links:

    name: Home url: /
    name: About url: /about
    name: Posts url: /posts

© 2025 Dhirandar

